CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER                                   NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)                              NOT NULL,
    type           VARCHAR(20)                               NOT NULL,
    script         VARCHAR(1000)                             NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)                              NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER                                   NOT NULL,
    success        BOOLEAN                                   NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE users
(
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name         VARCHAR(255)                            NOT NULL,
    last_name          VARCHAR(255)                            NOT NULL,
    profile_image_link VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE categories
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id)
);

CREATE TABLE exercises
(
    exercise_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exercise_name       VARCHAR(255)                            NOT NULL,
    description         VARCHAR(255)                            NOT NULL,
    exercise_video_link VARCHAR(255),
    CONSTRAINT pk_exercise_library PRIMARY KEY (exercise_id)
);

CREATE TABLE testimonials
(
    testimonial_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    testimonial    VARCHAR(1500)                           NOT NULL,
    user_id        BIGINT,
    CONSTRAINT pk_testimonials PRIMARY KEY (testimonial_id)
);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_category_name UNIQUE (category_name);

ALTER TABLE exercises
    ADD CONSTRAINT uk_4kuvnyygy6ngu6d5oqxjtsh0q UNIQUE (exercise_video_link);

ALTER TABLE testimonials
    ADD CONSTRAINT uk_h69y6e5g7btbnr6d9aesg2535 UNIQUE (user_id);

CREATE TABLE exercise_categories
(
    exercise_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT pk_exercise_categories PRIMARY KEY (exercise_id, category_id)
);

ALTER TABLE exercise_categories
    ADD CONSTRAINT fk_exercise_categories_on_category FOREIGN KEY (category_id) REFERENCES categories (category_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE exercise_categories
    ADD CONSTRAINT fk_exercise_categories_on_exercise FOREIGN KEY (exercise_id) REFERENCES exercises (exercise_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testimonials
    ADD CONSTRAINT fkdygt44q9i0mjmmxxgvtl2ytce FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;