CREATE TABLE categories
(
    category_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(32)                              NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id)
);

CREATE TABLE exercise_categories
(
    exercise_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    CONSTRAINT pk_exercise_categories PRIMARY KEY (exercise_id, category_id)
);

CREATE TABLE exercise_library
(
    exercise_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exercise_name VARCHAR(255)                             NOT NULL,
    description   VARCHAR(255)                             NOT NULL,
    video_type    VARCHAR(255),
    video         OID,
    CONSTRAINT pk_exercise_library PRIMARY KEY (exercise_id)
);

CREATE TABLE testimonials
(
    testimonial_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name     VARCHAR(255),
    last_initial   VARCHAR(255),
    testimonial    VARCHAR(255),
    CONSTRAINT pk_testimonials PRIMARY KEY (testimonial_id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_category_name UNIQUE (category_name);

ALTER TABLE exercise_categories
    ADD CONSTRAINT FK_EXERCISE_CATEGORIES_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (category_id);

ALTER TABLE exercise_categories
    ADD CONSTRAINT FK_EXERCISE_CATEGORIES_ON_EXERCISE FOREIGN KEY (exercise_id) REFERENCES exercise_library (exercise_id);